from .s3 import AWSS3Handler
from .ec2 import AWSEC2Handler
from .iam import AWSIAMHandler
from .api_gateway import AWSAPIGatewayHandler
from .cloudwatch import AWSCloudWatchHandler
from .elasticache import AWSElastiCacheHandler
from .elb import AWSElasticLoadBalancerHandler
from .rds import AWSRDSHandler
from .serverless import AWSLambdaHandler